---
title: "R_Practice"
author: "James Strange"
date: "February 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
trees = read.csv('https://raw.githubusercontent.com/dmcglinn/quant_methods/gh-pages/data/treedata_subset.csv')
weeds = read.csv('http://dmcglinn.github.io/quant_methods/data/milkweeds.csv')
library(MASS)
library(vegan)
library(gridExtra)
library(scatterplot3d)
library(ggplot2)
```

## This is a sandbox file I've created for practicing stuff I learn in class. 

```{r}
#Univariate Analysis Practice
sapply(trees, class)
sapply(weeds, class)
par(mfrow = c(1,2))
boxplot(plant_ht_cm ~ trt, data = weeds, xlab = "Treatment", ylab = "Plant Height (cm)", main = "Treatment vs. Plant Height")
boxplot(fruit_mass_mg ~ trt, data = weeds, xlab = "Treatment", ylab = "Fruit Mass (mg)", main = "Treatment vs Fruit Mass")
par(mfrow = c(1,1))
panel.cor <- function(x, y, digits = 2, prefix = "", cex.cor=3, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(0, 1, 0, 1))
    r <- abs(cor(x, y))
    txt <- format(c(r, 0.123456789), digits = digits)[1]
    txt <- paste0(prefix, txt)
    if(missing(cex.cor)) 
        cex.cor <- 0.8/strwidth(txt)
    text(0.5, 0.5, txt, cex = cex.cor)
}
pairs(fruit_mass_mg ~ trt + plant_ht_cm, data = weeds, lower.panel = panel.smooth, upper.panel = panel.cor)

```


```{r}
fruit.mass.mod = lm(fruit_mass_mg ~ plant_ht_cm, data = weeds)
plot(fruit_mass_mg ~ plant_ht_cm, data = weeds, xlab = "Plant Height (cm)", ylab = "Fruit Mass (mg)", main = "Plant Height vs. Fruit Mass")
abline(fruit.mass.mod)
```

```{r}
main.fruit.mod = lm(fruit_mass_mg ~ trt + plant_ht_cm, data = weeds)
int.fruit.mod = lm(fruit_mass_mg ~ trt + plant_ht_cm + trt*plant_ht_cm, data = weeds)
AIC(main.fruit.mod)
AIC(int.fruit.mod)
stepAIC(main.fruit.mod)
summary(main.fruit.mod)
```



```{r}
#Multivariate ordination practice
library(dummies)
source('https://raw.githubusercontent.com/dmcglinn/quant_methods/gh-pages/scripts/utility_functions.R')
uni_sp = unique(trees$spcode)
uni_site = unique(trees$plotID)
comm = tapply(trees$cover,
              INDEX = list(trees$plotID, trees$spcode),
              mean)
comm = ifelse(is.na(comm), 0, comm)
comm[1:5, 1:5]
uni_sp = unique(trees$spcode)
sp_sum = apply(comm, 2, sum)
site_sum = apply(comm, 1, sum)
par(mfrow=c(2,2))
hist(sp_sum)
col = colorRamp(c('red', 'orange', 'blue'))
sp_cols = col(length(uni_sp))
plot(sp_sum[order(sp_sum, decreasing=T)], type='o', col='red', lwd=2,
     xlab='Sp Rank', ylab='Sum Cover')
hist(site_sum)
plot(site_sum[order(site_sum, decreasing=T)], type='o', col='red', lwd=2,
     xlab='Site Rank', ylab='Sum Cover')







```




```{r}
#Explanatory matrix
cols_to_keep = c('elev', 'tci', 'streamdist', 'disturb', 'beers')
env = aggregate(trees[ , cols_to_keep], by = list(trees$plotID), function(x) x[1])
row.names(env) = env[ , 1]
env = env[ , -1]
plot(tree_mds, type='n')
text(tree_mds, 'sp', cex=.5)
 # generate vector of colors 
color_vect = rev(terrain.colors(6))[-1]
points(tree_mds, 'sites', pch=19, 
        col=color_vect[env$elev])
legend('topright', paste("Moisture =", 1:5, sep=''), 
        col=color_vect, pch=19)
```
